<?php
include_once("assets/php/funkcije.php");
?>
<!doctype html>
<html lang="sr">
    <head>
        <!-- meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="robots" content="Index, Follow">
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="copyright" content="">
        <meta name="Audience" content="all">
        <meta name="distribution" content="global">
        <meta name="theme-color" content="#EBEBEB" >
        <meta name="language" content="sr">

        <link rel="preload" as="image" href="important.png">

        <link href="" rel="canonical">

        <link href="" rel="icon">
        <link href="" rel="apple-touch-icon">

        <title>Hello, world!</title>

        <link rel="stylesheet" href="assets/css/style.min.css">

        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
            {
                "@context": "https://schema.org/",
                "@type": "WebPage",
                "name": "Privatni casovi programiranja online",
                "mainEntityOfPage": {
                    "@type": "WebPage",
                    "@id": "http://privatni-casovi-programiranja-online.rs/"
                },
                "headline": "Privatni casovi programiranja online",
                "description": "Nudim privatne casove programiranja onima koji zele da nauce osnove programiranja a nemaju nikakvo prethodno iskustvo, kao i onima kojima je potrebna dodatna obuka. Casovi programiranja su takodje predvidjeni i za osnovce, srednjoskolce, vise skole i fakultete.",
                "image": "https://www.privatni-casovi-programiranja-online.rs/assets/img/programming.png",
                "author": {
                    "@type": "Person",
                    "name": "Nemanja",
                    "url": ""
                },
                "publisher": {
                    "@type": "Organization",
                    "name": "",
                    "logo": {
                        "@type": "ImageObject",
                        "url": ""
                    }
                },
                "datePublished": "2022-11-23"
            }
        </script>
    </head>
    <body>
        <div class="container-fluid">

            <div class="row">
                <?php include_once("assets/php/navigacija.php"); ?>
            </div>

            <div class="row mt-1">
                <div class="col-12 breadcrumb-wrapper">
                    <ul id="breadcrumb">
                        <li><a href="#"><span class="icon icon-home"> </span></a></li>
                        <li><a href="#"><span class="icon icon-beaker"> </span> Home</a></li>
                        <li><a href="#"><span class="icon icon-double-angle-right"></span>page</a></li>
                    </ul>
                </div>
            </div>

            <div class="row">
                <?php include_once("assets/php/footer.php"); ?>
            </div>

        </div>


        <script src="assets/js/script.js" defer></script>
    </body>
</html>