<?php
include_once("Connection.php");
include_once("Message.php");
include_once("Email.php");
include_once("UserInput.php");
include_once("Functions.php");
include_once("Templates.php");
include_once("Validator.php");
include_once("model/Model.php");
include_once("model/UserModel.php");
include_once("model/User.php");